---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 11.8.2
  use_vagrant_berkshelf_plugin: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: agent
    run_list:
      - recipe[martinisoft-datadog::agent]
    data_bag_path: test/integration/data_bags
    encrypted_data_bag_secret_key_path: test/integration/data_bags/encrypted_data_bag_secret
    attributes:
